#!/bin/bash

###############################################################################
#		(C) 2009-2011 hyperclock (aka Jimmy M. Coleman)
#        website	:		www.cybernux.org
#        email		:		hyperclock(at)cybernux(dot)org
#        svn		:		http://xp-dev.com/svn/ForkForge/
#        dev		:		http://dev.cybernux.org
#
###############################################################################
###############################################################################
#    ForkMason - Scripts designed to build Cybernux Linux® based on Debian.
#
#    ForkMason is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ForkMason is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General
#    Public License along with ForkMason.  If not, see
#    <http://www.gnu.org/licenses/>.
#
################################################################################
################################ INFO ##########################################
#
#       Derived from the scripts used by the gNewSense Project.
#       See the original scripts at http://gnewsense.org
#
#       Original (C) 2006 - 2009  Brian Brazil
#
#################################################################################
#    Copyright (C) 2009  Karl Goetz
#################################################################################

cd `dirname $0`/..
. config

# Loop through all arches in use
for GENARCH in $ALL_REPO_ARCHES; do
		# Generate contents files for each section (experimental)
		for SECTION in '' -security $EXTRAS; do
			apt-ftparchive contents $REPODST/pool |gzip > $REPODST/dists/$BASE_RELEASE$SECTION/Contents-$GENARCH.gz
		done
done
