#!/bin/bash

###############################################################################
#    (C) 2009-2011 hyperclock (aka Jimmy M. Coleman)
#	 Website:	http://forkmason.berlios.de
#	 eMail:		hyperclock(at)web(dot)de
#	 PROJECT:	http://developer.berlios.de/projects/forkmason/
# 
###############################################################################
###############################################################################
#    ForkMason - Scripts designed to build a Linux OS based on Debian.
#
#    ForkMason is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ForkMason is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General 
#    Public License along with ForkMason.  If not, see 
#    <http://www.gnu.org/licenses/>.
#
################################################################################

