#!/bin/bash

###############################################################################
#    (C) 2009-2011 hyperclock (aka Jimmy M. Coleman)
#	 Website:	http://forkmason.berlios.de
#	 eMail:		hyperclock(at)web(dot)de
#	 PROJECT:	http://developer.berlios.de/projects/forkmason/
# 
###############################################################################
###############################################################################
#    ForkMason - Scripts designed to build a Linux OS based on Debian.
#
#    ForkMason is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ForkMason is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General 
#    Public License along with ForkMason.  If not, see 
#    <http://www.gnu.org/licenses/>.
#
################################################################################

# -----------------------
# Get distro information
# -----------------------
. config

# ------------------------------
# Create Repository Destination
# -----------------------------
mkdir -p $REPO_DEST/conf

cd $REPO_DEST

### CHANGE TO FIT YOUR REPO
### WE USE "main bound community"
### - you may want to change or revert back

cat >  conf/distributions <<EOF
Origin: $DIST_NAME
Label: $DIST_NAME
Codename: ${RELEASE}-security
Update: Upstream-security
Architectures: $REPO_ARCHES source
Components: main community bound
SignWith: $REPO_KEY
DscIndices: Sources Release . .gz

Origin: $DIST_NAME
Label: $DIST_NAME
Codename: $RELEASE
Update: Upstream
Architectures: $REPO_ARCHES source
Components: main community bound
UDebComponents: main
SignWith: $REPO_KEY
DscIndices: Sources Release . .gz
EOF

cat >  conf/updates <<EOF
Name: Upstream-security
Method: $SEC_MIRROR
Suite: $SEC_RELEASE
Components: main>main contrib>community
VerifyRelease: blindtrust

Name: Upstream
Method: $MIRROR
Suite: $MIRROR_RELEASE
Components: main>main contrib>community non-free>bound
VerifyRelease: blindtrust
EOF


if [ 1 == $UPDATES ]; then
cat >> conf/updates <<EOF

Name: Upstream-updates
Method: $UPD_MIRROR
Suite: $UPD_RELEASE
Components: main>main contrib>community non-free>bound
VerifyRelease: blindtrust
EOF

cat >>  conf/distributions <<EOF

Origin: $DIST_NAME
Label: $DIST_NAME
Codename: $RELEASE-updates
Update: Upstream-updates
Architectures: $REPO_ARCHES source
Components: main community bound
SignWith: $REPO_KEY
DscIndices: Sources Release . .gz
EOF
fi

if [ 1 == $BACKPORTS ]; then
cat >> conf/updates <<EOF

Name: Upstream-backports
Method: $BP_MIRROR
Suite: $BP_RELEASE
Components: main>main
VerifyRelease: blindtrust
EOF

cat >>  conf/distributions <<EOF

Origin: $DIST_NAME
Label: $DIST_NAME
Codename: $RELEASE-backports
Update: Upstream-backports
Architectures: $REPO_ARCHES source
Components: main
SignWith: $REPO_KEY
DscIndices: Sources Release . .gz
EOF
fi;


mkdir -p $REPO_DEST/cdimage
mkdir -p $REPO_DEST/apt/{var,lists/partial,cache/archives/partial}
touch $REPO_DEST/apt/status
