#!/bin/bash

# ----------------------------------------------------------------------
# ForkMasonMM			::	fork Debian Archive
# Copyright				::	(C) 2011-2012 by the Cybernux Linux® DevTeam.
# Cybernux Linux® WWW	::	http://www.cybernux.org/
# Cybernux Linux® Dev	::	http://dev.cybernux.org/
# SVN Archive			::	http://svn.berlios.de/wsvn/forkmason
# ----------------------------------------------------------------------
# Based on:
# The gNewSense Builder - http://gnewsense.org/Builder (GPLv2)
# ----------------------------------------------------------------------
# LICENSE:
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------

## ----------------------
## Check if you are ROOT
## ----------------------
if [ $UID != 0 ]; then
	echo 'This script must be run as root'
	exit 1
fi

# -------------------------------
# Set Debuuging
# If you want less debugging 
# info to be printed out,
# change this line to 'set +ex'
# ------------------------------
set -ex

## --------------------
## UPSTREAM AREA
## This is where you
## get your pkgs from
## --------------------

# -------------------
# Main Upstream repo
# -------------------
MIRROR="http://ftp.de.debian.org/debian/"
MIRROR_DIST="wheezy"
MIRROR_COMP="main contrib non-free"

# -------------------
# Updates Upstream repo
# -------------------
UPD_MIRROR="http://ftp.de.debian.org/debian-security"
UPD_MIRROR_DIST="wheezy-updates"
UPD_MIRROR_COMP="main contrib non-free"

# --------------------------
# Backports Upstream repo
# --------------------------
BP_MIRROR="http://ftp.de.debian.org/debian-backports"
BP_MIRROR_DIST="wheezy-backports"
BP_MIRROR_COMP="main contrib non-free"

# -------------------
# Mate Upstream repo
# -------------------
MATE_MIRROR="http://repo.mate-desktop.org/debian"
MATE_MIRROR_DIST="wheezy"
MATE_MIRROR_COMP="main"


# -------------------
# Other Upstream repo
# -------------------
OTH_MIRROR=""
OTH_MIRROR_DIST=""
OTH_MIRROR_COMP=""


## ---------------------
## DISTRO CONFIGURATION
## ---------------------

# -----------------------
# Your Distribution Name
# -----------------------
DIST_NAME_FULL="Cybernux Linux®"
DIST_NAME="Cybernux"
DIST_NAME_L=`echo $DIST_NAME | tr 'A-Z' 'a-z'`

# ----------------------
# Your Releade Codename
# ---------------------
BASE_RELEASE=othala
[ -z $RELEASE ] && RELEASE=$BASE_RELEASE

# ------------------------------
# Not really needed - but cool
# -----------------------------
TAG_LINE=""

# -------------------------------
# This is the 8 character key ID,
# not the full fingerprint
# -------------------------------
REPO_KEY=84984D96

# -----------------------------------
# Name and email address for changes. 
# Syntax is important.
# -----------------------------------
export MAINT_INFO='Jimmy M. Coleman <hyperclock@cybernux.org>'

#--------------------------------------
# enable/disable backports and updates
# enable=1   disable=0
# ------------------------------------
UPDATES=0
BACKPORTS=0

# ------------
# Repo Arches
# ------------
REPO_ARCHES="i386 amd64"

## --------------------
## ARTWORK & Packaging
## --------------------

# -----------------------------------
# Don't choose black or yellow color
# -----------------------------------
LOGO_LETTER=c
LOGO_COLOUR=blue

# ------
# PATHS
# ------
WORK_DIR=$BASEDIR/tmp
LIVE_DIR=$BASEDIR/livecd
REPO_DEST=$BASEDIR/$DIST_NAME_L

# Version numbers to be appended to generated .debs 
# Mostly used during development (Increment these versions when making a change to the package)
APT_VERSION=1
BASE_FILES_VERSION=1
ARTWORK_VERSION=1
KERNEL_VERSION=1
ICEWEASEL_VERSION=1
GNOME_DESKTOP_VERSION=1
GNOME_PANEL_VERSION=1

## -----------------
## MID STREAM AREA
## -----------------

# -------------------
# Where things go on 
# the Build Server
# ------------------
BASEDIR=/srv/$DIST_NAME_L

# ---------------------------
# Where the buildscripts and 
# livecd pull sources from
# --------------------------
REPO_APT=http://127.0.0.1/$DIST_NAME_L

## ----------------
## LIVE CD STUFF
## ----------------

# --------------------
# Live CD/DVD Version
# -------------------
LIVE_VERS=1.0

## -------------
## ARCHIVE AREA
## -------------

#-------------------------------------------
# Primary mirror should be archive.$DOMAIN, 
# secondaries are CC.archive.$DOMAIN
# Security host will be security.$DOMAIN 
# and CC.security.$DOMAIN
# -----------------------------------------
DOMAIN=cybernux.org

# -----------------------------------
# Where to push the repo and livecds
# -----------------------------------
RSYNC_DEST=USER@repo.$DOMAIN:/web/$DIST_NAME_L/

# ----------------------------
# Extra options for rsyncing 
# up cds, -va is assumed
# ---------------------------
RSYNC_OPTIONS="--partial"


## -----------------------------
## EDIT ONLY WHERE NOTED
## Unless you know what you are
## If your changes work, report 
## back to us - we may use it.
## -----------------------------

# ---------------------
# Which extras to build
# ---------------------
if [ 1 == $UPDATES ]; then EXTRAS="-updates"; fi
if [ 1 == $BACKPORTS ]; then EXTRAS="$EXTRAS -backports"; fi

# -------------------------------------------
# CHANGE the arch we are building. 
# Defaults to i386 if nothing is specified
# Valid strings are "amd64" and "i386"
# -------------------------------------------
if [ -z $BUILD_ARCH ]; then
	BUILD_ARCH="i386"
fi

# -------------------------------------------------
# DON'T CHANGE THIS - may break things
# This sets variables for different 
# sections of the $BUILDARCH variable
# Using case to be a little forgiving about input
# -------------------------------------------------
case $BUILDARCH in
	386 | i386 | I386 | ia32 | IA32)
		export HOST_ARCH="i386";
		export KERNEL_ARCH="386";
		export DPKG_OPTS='-rfakeroot -e"$MAINT_INFO" -m"$MAINT_INFO" -us -uc -ai386';
	;;
	amd64 | AMD64)
		export HOST_ARCH="amd64";
		export KERNEL_ARCH="amd64";
		export DPKG_OPTS='-rfakeroot -e"$MAINT_INFO" -m"$MAINT_INFO" -us -uc -B -aamd64';
	;;
	*)
	echo -e "\n\nERROR\! invalid arch\!\n\n"
	exit 1
	;;
esac

# --------------------------------
# CHANGE:
# this is the Kernel version used 
# --------------------------------
case $(tr A-Z a-z <<<$MIRROR_DIST) in
	"wheezy")
		export KERNEL_RELEASE="3.2.0"
		;;
	*)
		exit 1
		;;
esac



