#!/bin/bash

###############################################################################
#		(C) 2009-2011 hyperclock (aka Jimmy M. Coleman)
#        website	:		www.cybernux.org
#        email		:		hyperclock(at)cybernux(dot)org
#        svn		:		http://xp-dev.com/svn/ForkForge/
#        dev		:		http://dev.cybernux.org
#
###############################################################################
###############################################################################
#    ForkMason - Scripts designed to build Cybernux Linux® based on Debian.
#
#    ForkMason is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ForkMason is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General
#    Public License along with ForkMason.  If not, see
#    <http://www.gnu.org/licenses/>.
#
################################################################################
################################ INFO ##########################################
#
#       Derived from the scripts used by the gNewSense Project.
#       See the original scripts at http://gnewsense.org
#
#       Original (C) 2006 - 2009  Brian Brazil
#
#################################################################################

# -----------------------------------------
# This is the config for Cybernux Linux®, 
# alter as appropriate for your own distro
# -----------------------------------------

# -----------------------
# Check if you are root
# -----------------------

if [ $UID != 0 ]; then
	echo 'This script must be run as root'
	exit 1
fi

# ---------------------------------------------
# If you want less debugging information 
# to be printed out while doing a
# ForkMason run, change this line to 'set +ex'
# ---------------------------------------------
set -ex

### -------------------------------------------
### NOTE:    For kde download before anything 
### libbogl-dev # Chris Fernandez
### COPY & PASTE THIS INTO THE CLI -
### ONLY ON FIRST USAGE.
### aptitude install libbogl-dev
### -------------------------------------------

## ----------
## UPSTREAM
## ----------
# ----------------------------
# Path to your Debian mirror
# ---------------------------
#MIRRORLOCAL=/srv/debian-mirror/

# -------------------------------
# Where to get updated upstream 
# packages from. Currently only 
# supports http
# ------------------------------
# -------------------
# Main Upstream repo
# -------------------
MIRROR="http://ftp.de.debian.org/debian/"
MIRROR_DIST="wheezy"
MIRROR_COMP="main contrib non-free"

# -------------------
# Updates Upstream repo
# -------------------
UPD_MIRROR="http://ftp.de.debian.org/debian-security"
UPD_MIRROR_DIST="wheezy-updates"
UPD_MIRROR_COMP="main contrib non-free"

# --------------------------
# Backports Upstream repo
# --------------------------
BP_MIRROR="http://ftp.de.debian.org/debian-backports"
BP_MIRROR_DIST="wheezy-backports"
BP_MIRROR_COMP="main contrib non-free"

# -------------------
# Mate Upstream repo
# -------------------
MATE_MIRROR="http://repo.mate-desktop.org/debian"
MATE_MIRROR_DIST="wheezy"
MATE_MIRROR_COMP="main"


# -------------------
# Other Upstream repo
# -------------------
OTH_MIRROR=""
OTH_MIRROR_DIST=""
OTH_MIRROR_COMP=""

## -------------------------------
## DISTRO SPECIFIC CONFIGURATION
## -------------------------------
# -------------------------------
# May break if you use anything 
# other than letters and numbers
# If you change $DIST_NAME you 
# may need to modify 
# META_desktop_ADD or create
# your own artwork packages.
# -------------------------------
## ---------------------
## DISTRO CONFIGURATION
## ---------------------

# -----------------------
# Your Distribution Name
# -----------------------
DIST_NAME_FULL="Cybernux Linux®"
DIST_NAME="Cybernux"
DIST_NAME_L=`echo $DIST_NAME | tr 'A-Z' 'a-z'`

# --------------------
# What is the codename
# for our release?
# --------------------
BASE_RELEASE=othala
[ -z $RELEASE ] && RELEASE=$BASE_RELEASE

# ------------------------------
# Not really needed - but cool
# -----------------------------
TAG_LINE=""

# -------------------------------
# This is the 8 character key ID,
# not the full fingerprint
# -------------------------------
REPO_KEY=84984D96

# -----------------------------------
# Name and email address for changes. 
# Syntax is important.
# -----------------------------------
export MAINT_INFO='Jimmy M. Coleman <hyperclock@cybernux.org>'

# ---------------------------------------
# Do you want to ENABLE(1) or DISABLE(0) 
# backports and updates?
# ---------------------------------------
UPDATES=0
BACKPORTS=0

# ------------------------------
# Which arches dou want in your 
# repository (list all of them)
# ------------------------------
REPO_ARCHES="i386 amd64"

## -----------
## MID STREAM
## ----------
# ----------------------------------
# Where things go on the filesystem
# ----------------------------------
BASEDIR=/srv/$DIST_NAME_L

# ------------------------------
# Where the buildscripts 
# and livecd pull sources from
# ------------------------------
REPOAPT=http://127.0.0.1/$DIST_NAME_L

## ----------
## LIVE CD
## ---------
LIVECD_VERSION=1.0

## ------------------
## ARCHIVE AND MEDIA
## ------------------
# ----------------------------------------------------------------
# Primary mirror should be repo.$DOMAIN, 
# secondaries are CC.repo.$DOMAIN
# Security host will be security.$DOMAIN and CC.security.$DOMAIN
# ----------------------------------------------------------------
DOMAIN=cybernux.org

# ----------------------------------
# Optional bittorrent announce list 
# (btmakemetafile.bittornado --help)
# ----------------------------------
BITTORRENT_ANNOUNCE_LIST=''

# -----------------------------------
# Where to push the repo and livecds
# -----------------------------------
RSYNC_DEST=sandbox@repo.$DOMAIN:/srv/$DIST_NAME_L/
CD_RSYNC_DEST=sandbox@cdimage.$DOMAIN:/srv/$DIST_NAME_L/

# ---------------------------
# Extra options for rsyncing 
# up cds, -va is assumed
# ---------------------------
RSYNC_OPTIONS="--partial"

## -------
## ARTWORK
## --------
LOGO_LETTER=c

# -----------------------------
# Don't choose black or yellow
# -----------------------------
LOGO_COLOUR=blue

# ---------------------------------
# Changes to be made to the 
# ubuntu-minimal etc. and packages
# ---------------------------------
META_minimal_ADD=""
META_standard_ADD="emacs nethack bsdgames build-essential"
META_desktop_ADD="discover read-edid"
META_desktop_ADD="${META_desktop_ADD} gthumb gnote aspell-en"
META_minimal_REMOVE=""
META_standard_REMOVE="popularity-contest friendly-recovery"
META_desktop_REMOVE=""
META_desktop_REMOVE="${META_desktop_REMOVE "
META_desktop_REMOVE="${META_desktop_REMOVE} tomboy f-spot"

# Packages to install on the live cd not pulled in by META_* changes
LIVECD_EXTRAS="xresprobe binutils-static gvfs-fuse gparted jfsutils ntfsprogs xfsprogs vim"

# -------------------------
# Change name of Iceweasel
# (Firefox) to reflect
# your Distro
# -------------------------
ICEWEASEL_NAME=SnoWolf

# ---------------------------------------
# Extra packages to add to the source cd
# ---------------------------------------
CDSOURCE_ADD="forkforge"

# ----------------------------------------
# Extra packages to install in the chroot
# ----------------------------------------
CHROOT_EXTRA_PACKAGES="cdbs python-dev python-distutils-extra python-central ccache"

# ---------------------------------------------------------------------------
# Set it to 1 if you want to use ccache in the chrooted environment.
# ccache is turned off by default because it is useful only for development
# and may increase first compilation time.
# ---------------------------------------------------------------------------
USECCACHE=0

# ----------------------------------------------------
# Version numbers to be appended to generated .debs 
# Mostly used during development (Increment these 
# versions when making a change to the package)
# ---------------------------------------------------
APT_VERSION=1
BASE_FILES_VERSION=1
UPDATE_MANAGER_VERSION=1
ARTWORK_VERSION=1
META_VERSION=1
KERNEL_VERSION=1
FORKMASON_VERSION=1
KDEFAULT_SETTINGS_VERSION=1
KMETA_VERSION=1
ICEWEASEL_VERSION=1
GNOME_DESKTOP_VERSION=1
YELP_VERSION=1
HUMAN_ICON_THEME_VERSION=1
GNOME_PANEL_VERSION=1
EPIPHANY_BROWSER_VERSION=1
PYTHON_APT_VERSION=1
THUNDERBIRD_VERSION=1
TEXLIVE_EXTRA_VERSION=1
TEXLIVE_BIN_VERSION=1
TEXLIVE_BASE_VERSION=1
VLC_VERSION=1
CIA_SCRIPTS_VERSION=1
LIBGSM_VERSION=1

## ------
## PATHS
## ------
WORK_DIR=$BASEDIR/tmp

# ----------------------------------
# Where to put stuff for creating 
# the livecd, and creating packages
# ----------------------------------
LIVE_CD_DIR=$BASEDIR/livecd
REPO_DEST=$BASEDIR/$DIST_NAME_L

# -----------------------------------------
# Space separated list of repo components. 
# Put the default first.
# -----------------------------------------
COMPONENTS="main community bound"

# ------------May not be needed for us -------------------------
# Allow for local customisations
#if [ -r config.local ]; then . config.local; fi

#if [ -r config.auto ]; then . config.auto; else exit 1; fi
# --------------------------------------------------------------


# What arch are we building? Defaults to i386 is nothing specified
# via the calling environment
# Currently, valid strings are "amd64" and "i386"
if [ -z $BUILD_ARCH ]; then
	BUILD_ARCH="i386"
fi

# ---------------------------------------------------------------------------
### DO NOT EDIT THIS BELOW
### It exists to set a number of variables automatically according to
### preferences in config and config.
### ---------------------------------------------------------------------------
# ------------------------------------
# Which extras (aka variant) to build
# ------------------------------------
if [ 1 == $UPDATES ]; then EXTRAS="-updates"; fi
if [ 1 == $BACKPORTS ]; then EXTRAS="$EXTRAS -backports"; fi

# --------------------------------------------------------------------------
# This sets variables for different sections of builder to use based on the
# $BUILD_ARCH variable from above
# Using case to be a little forgiving about input
# --------------------------------------------------------------------------
case $BUILD_ARCH in
	386 | i386 | I386 | ia32 | IA32)
		export GNS_HOST_ARCH="i386";
		export KERNEL_ARCH="386";
		export DPKG_OPTS='-rfakeroot -e"$MAINT_INFO" -m"$MAINT_INFO" -us -uc -ai386';
	;;
	amd64 | AMD64)
		export GNS_HOST_ARCH="amd64";
		export KERNEL_ARCH="amd64";
		export DPKG_OPTS='-rfakeroot -e"$MAINT_INFO" -m"$MAINT_INFO" -us -uc -B -aamd64';
	;;
	*)
	echo -e "\n\nERROR\! invalid arch\!\n\n"
	exit 1
	;;
esac

case $(tr A-Z a-z <<<$MIRROR_DIST) in
	"wheezy")
		export KERNEL_RELEASE="3.2.0"
		;;
	*)
		exit 1
		;;
esac

# ------------------------------------
# Without this, the diff cleaning for 
# gen-linux will break. Probably 
# affects other stuff too.
# -------------------------------------
LANG=C

