#!/bin/bash

###############################################################################
#		(C) 2009-2011 hyperclock (aka Jimmy M. Coleman)
#        website	:		www.cybernux.org
#        email		:		hyperclock(at)cybernux(dot)org
#        svn		:		http://xp-dev.com/svn/ForkForge/
#        dev		:		http://dev.cybernux.org
#
###############################################################################
###############################################################################
#    ForkMason - Scripts designed to build Cybernux Linux® based on Debian.
#
#    ForkMason is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ForkMason is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General
#    Public License along with ForkMason.  If not, see
#    <http://www.gnu.org/licenses/>.
#
################################################################################
################################ INFO ##########################################
#
#       Derived from the scripts used by the gNewSense Project.
#       See the original scripts at http://gnewsense.org
#
#       Original (C) 2006 - 2009  Brian Brazil
#
#################################################################################
#       Copyright (C) 2006 - 2009  Brian Brazil
#       Copyright (C) 2009  Karl Goetz
#       Copyright (C) 2010  Sam Geeraerts
#################################################################################


. config

discover_version(){
	# $1 package source name
	# $2 on disk repository ($MIRRORLOCAL or $REPO_DEST)
	# $3 Release ($MIRROR_DIST or $BASE_RELEASE)
	# $4 sub-release (-security,-updates,-backports)

	# Find "Package:", then find "Version:" and print the second field
	awk -v srcpkg=$1 'BEGIN { package_found = 0 }
/^Package:/ {if ($2 == srcpkg) package_found = 1}
/^Version:/ {if (package_found == 1) { print $2; exit; } }' $2/dists/$3$4/*/source/Sources
}

get_binaries(){
  local codename=$1
  local src=$2
  
  # Upstream codename.
  local ucodename=$(echo "$codename" | sed "s/$RELEASE/$MIRROR_DIST/")  

  local binaries=$(awk -v pkg="$src" 'BEGIN { package_found = 0 }
/^Package:/ { if ($2 == pkg) package_found = 1 }
/^Binary:/ { if (package_found == 1 ) { for (i=2; i<=NF; i++) printf ("%s", $i);
exit; } }' \
"$MIRRORLOCAL"/dists/"$ucodename"/*/source/Sources)
  binaries=$(echo "$binaries" | tr ',' ' ')

  # Dirty hack (hopefully temporary).
  if [ -z "$binaries" ] ; then
    binaries=$(egrep "^$src=" binaries | cut -d "=" -f 2)
  fi

  echo "$binaries"
}

get_section(){
  local codename=$1
  local src=$2 # Source package name
  local bin=$3 # Binary package name (optional)
  
  local section=""
  # Upstream codename.
  local ucodename=$(echo "$codename" | sed "s/$RELEASE/$MIRROR_DIST/")
  
  if [ -n "$bin" ] ; then
    section=$(awk -v pkg="$bin" 'BEGIN { package_found = 0 }
/^Package:/ { if ($2 == pkg) package_found = 1 }
/^Section:/ { if (package_found == 1) { print $2; exit; } }' \
"$MIRROR"/dists/"$ucodename"/*/binary-"$GNS_HOST_ARCH"/Packages)
    if [ -z "$section" ] ; then
      section=$(awk -v pkg="$bin" 'BEGIN { package_found = 0 }
/^Package:/ { if ($2 == pkg) package_found = 1 }
/^Section:/ { if (package_found == 1) { print $2; exit; } }' \
"$MIRROR"/dists/"$ucodename"/*/debian-installer/binary-"$GNS_HOST_ARCH"/Packages)
    fi
    if [ -z "$section" ] ; then
      section=$(egrep -e "^$bin Section " override.bin | cut -d ' ' -f 3)
    fi
  else
    section=$(awk -v pkg="$src" 'BEGIN { package_found = 0 }
/^Package:/ { if ($2 == pkg) package_found = 1 }
/^Section:/ { if (package_found == 1) { print $2; exit; } }' \
"$MIRROR"/dists/"$ucodename"/*/source/Sources)
    if [ -z "$section" ] ; then
      section=$(egrep -e "^$src Section " override.src | cut -d ' ' -f 3)
    fi
  fi
  
  echo "$section"
}

set_sections(){
  local codename=$1
  local src=$2 # Source package name
  local bin=$3 # Binary package name (optional)
  
  local section=''
  local binaries=''
  
  section=$(get_section "$codename" "$src")
  if [ -n "$section" ] ; then
    echo "$src" Section "$section" >> "$REPO_DEST"/conf/override."$codename".src
  fi
  
  binaries=$(get_binaries "$codename" "$src")
  for b in $binaries ; do
    section=$(get_section "$codename" "$src" "$b")
    if [ -n "$section" ] ; then
      echo "$b" Section "$section" >> "$REPO_DEST"/conf/override."$codename".bin
    fi
  done
}

remove_sourceless(){
	local pkg=$1
	local codename=$2
	
	# Find versions of binary and source packages.
	# Binaries are debs or udebs. They either have the same name as the
	# source or refer to the source.
	# listfilter output = release|component|type: name version
	local deb_versions=$(reprepro -Vb $REPO_DEST -T deb listfilter $codename \
"Source (==$pkg) | Package (==$pkg)" | cut -d " " -f 3 | sort | uniq)
	local udeb_versions=$(reprepro -Vb $REPO_DEST -T udeb listfilter $codename \
"Source (==$pkg) | Package (==$pkg)" | cut -d " " -f 3 | sort | uniq)
	local bin_versions=$(echo $deb_versions $udeb_versions | sort | uniq)
	local src_versions=$(reprepro -Vb $REPO_DEST -T dsc listfilter $codename \
"Package (==$pkg)" | cut -d " " -f 3 | sort | uniq)
	
	# If a binary version has no source counterpart then delete all
	# binaries of that version.
	for bv in $bin_versions ; do
		local found=""
		for sv in $src_versions ; do
			if [ "$bv" = "$sv" ] ; then
				found=$bv
				break
			fi
		done
		if [ -z "$found" ] ; then
			reprepro -Vb $REPO_DEST -T deb removefilter $codename \
"Version (==$bv), (Source (==$pkg) | Package (==$pkg) )"
			reprepro -Vb $REPO_DEST -T udeb removefilter $codename \
"Version (==$bv), (Source (==$pkg) | Package (==$pkg) )"
		fi
	done
}

ensure_updated() {
	# Parameters:
	# $1 Upstream source package name
	# $2 Our source package name
	# $3 Release
	# $4 Build script
	# $5 Version in ./config.local

  set_sections "$3" "$2"

	# What version of this package do upstream have in our Sources file?
	UPSTREAM_VERSION=$(discover_version $1 $MIRROR $MIRROR_DIST $distro_release) ||true

	# What version of this package do we have in our Sources file?
	OUR_VERSION=$(discover_version $2 $REPO_DEST $BASE_RELEASE $distro_release |grep $DIST_NAME_L) ||true

	# If we are doing packages in -updates, and have a "non-existent" package, try -security
	if [ -z "$OUR_VERSION" -a "$distro_release" == "-updates" ]; then
		# Try to find a version in -security
		OUR_VERSION=$(discover_version $2 $REPO_DEST $BASE_RELEASE "-security" |grep $DIST_NAME_L) ||true

		# If OUR_VERSION is no longer empty (eg, its in -security)
		if [ -n $OUR_VERSION ]; then
			# Remove the version from -updates, since its probably non-free upstream stuff
			reprepro -Vb $REPO_DEST removesrc $RELEASE$distro_release $1
		fi
	fi

	# Find $DIST_NAME_L in $OUR_VERSION and delete everything to its left
	CURRENT_VERSION=${OUR_VERSION#*$DIST_NAME_L}

	if [ -n "$UPSTREAM_VERSION" ]; then # We have something to build from
		# We haven't built yet, or are out of date
		if [ -z "$OUR_VERSION" ] || dpkg --compare-versions $UPSTREAM_VERSION gt $OUR_VERSION; then 
			add_package "$2" "$5" "$UPSTREAM_VERSION" "$3" "$4"
		elif [ -n "$CURRENT_VERSION" ]; then
			# Has the version in the config file changed?
			if [ "$CURRENT_VERSION" -lt "$5" ]; then
				add_package "$2" "$5" "$UPSTREAM_VERSION" "$3" "$4"
			fi
		fi
	fi
	
	remove_sourceless $1 $RELEASE$distro_release
}

add_package() {
	# Parameters:
	# $1 Our source name
	# $2 Version in ./config
	# $3 Upstream version
	# $4 Release
	# $5 Build script

	# Does this release of this distribution have this source package?
	OUR_SOURCE=$(discover_version $1 $REPO_DEST $BASE_RELEASE $distro_release |grep $DIST_NAME_L$2) ||true

	if [ -z "$OUR_SOURCE" ]; then  # If we don't have this version, build it
		# Build it
		if [ 1 == "$DONT_CHROOT" ]; then
			# Some things need to manipulate the repo itself
			CHROOTDIR=$CHROOTDIR RELEASE=$4 VERSION="=$3" $5 || exit 1
		else
			chroot $CHROOTDIR bash -c "cd /forkmason && RELEASE=$4 VERSION='=$3' $CCACHE_PREFS $5" || exit 1
			reprepro --ignore=missingfile -Vb $REPO_DEST include $4 $CHROOTDIR/$WORK_DIR/*.changes
		fi
	fi
}

if [ $USECCACHE -eq 1 ]; then
	CCACHE_PREFS="CCACHE_DIR=/var/lib/ccache PATH=/usr/lib/ccache:$PATH"
fi

REDO=1
while [ $REDO -eq 1 ]; do	# If versions in the config change, we could need to redo the lot
	REDO=0
	reprepro --noskipold -V -b $REPO_DEST update || { echo "Repository update failed"; exit 1; }

	# Non-Free, or no valid use.
	for pkg in `cat packages-to-remove`; do
		for postfix in '' -security $EXTRAS; do
			reprepro -Vb $REPO_DEST removesrc $RELEASE$postfix $pkg
		done
	done

	for distro_release in '' -security $EXTRAS; do
		./update-chroot $distro_release

		CHROOTDIR=$WORK_DIR/$MIRROR_DIST$distro_release-$GNS_HOST_ARCH

    # Regenerate overrides on every run.
    for type in src bin; do
      OVERRIDE_FILE="$REPO_DEST"/conf/override."$RELEASE""$distro_release"."$type"
      rm -f "$OVERRIDE_FILE"
      touch "$OVERRIDE_FILE"
    done

		## -------
		## General
		## -------
		# ----------------------------------
		# ensure_updated srcname gnssrcname 
		# ----------------------------------
#		ensure_updated apt apt $RELEASE$distro_release ./gen-apt $APT_VERSION
#		ensure_updated cia-clients cia-clients $RELEASE$distro_release ./gen-cia-clients $CIA_SCRIPTS_VERSION
#		ensure_updated base-files base-files $RELEASE$distro_release ./gen-base-files $BASE_FILES_VERSION
#		ensure_updated example-content example-content $RELEASE$distro_release ./gen-example-content $EXAMPLE_CONTENT_VERSION
#		ensure_updated launchpad-integration launchpad-integration $RELEASE$distro_release ./gen-launchpad-integration $LAUNCHPAD_INTEGRATION_VERSION
#		ensure_updated linux linux $RELEASE$distro_release ./gen-linux $KERNEL_VERSION
#		ensure_updated linux-ubuntu-modules-$KERNEL_RELEASE linux-ubuntu-modules-$KERNEL_RELEASE $RELEASE$distro_release ./gen-linux-ubuntu-modules $LINUX_UBUNTU_MODULES_VERSION
#		ensure_updated module-init-tools module-init-tools $RELEASE$distro_release ./gen-module-init-tools $MODULE_INIT_TOOLS_VERSION
#		ensure_updated python-apt python-apt $RELEASE$distro_release ./gen-python-apt $PYTHON_APT_VERSION
#		ensure_updated texlive-base texlive-base $RELEASE$distro_release ./gen-texlive-base $TEXLIVE_BASE_VERSION
#		ensure_updated texlive-bin texlive-bin $RELEASE$distro_release ./gen-texlive-bin $TEXLIVE_BASE_VERSION
#		ensure_updated texlive-extra texlive-extra $RELEASE$distro_release ./gen-texlive-extra $TEXLIVE_EXTRA_VERSION
#		ensure_updated thunderbird thunderbird $RELEASE$distro_release ./gen-thunderbird $THUNDERBIRD_VERSION
#		ensure_updated ubiquity ubiquity $RELEASE$distro_release ./gen-ubiquity $UBIQUITY_VERSION
#		ensure_updated vlc vlc $RELEASE$distro_release ./gen-vlc $VLC_VERSION

		## ------
		## Gnome
		## ------
		# ----------------------------------
		# ensure_updated srcname gnssrcname 
		# ----------------------------------
#		ensure_updated app-install-data-ubuntu app-install-data-ubuntu $RELEASE$distro_release ./gen-app-install-data-ubuntu $APP_INSTALL_DATA_UBUNTU_VERSION
#		ensure_updated epiphany-browser epiphany-browser $RELEASE$distro_release ./gen-epiphany-browser $EPIPHANY_BROWSER_VERSION
#		ensure_updated gnome-desktop gnome-desktop $RELEASE$distro_release ./gen-gnome-desktop $GNOME_DESKTOP_VERSION
#		ensure_updated gnome-panel gnome-panel $RELEASE$distro_release ./gen-gnome-panel $GNOME_PANEL_VERSION
#		ensure_updated human-icon-theme human-icon-theme $RELEASE$distro_release ./gen-human-icon-theme $HUMAN_ICON_THEME_VERSION
#		ensure_updated ubuntu-artwork $DIST_NAME_L-artwork $RELEASE$distro_release ./gen-artwork $ARTWORK_VERSION
#		ensure_updated ubuntu-meta $DIST_NAME_L-meta $RELEASE$distro_release ./gen-meta $META_VERSION
#		ensure_updated yelp yelp $RELEASE$distro_release ./gen-yelp $YELP_VERSION

		## ----
		## KDE
		## ----
		# ----------------------------------
		# ensure_updated srcname gnssrcname 
		# ----------------------------------
#		 ensure_updated kubuntu-default-settings k$DIST_NAME_L-default-settings $RELEASE$distro_release ./gen-kdefault-settings $KDEFAULT_SETTINGS_VERSION
#		 ensure_updated kubuntu-meta k$DIST_NAME_L-desktop $RELEASE$distro_release ./gen-kmeta $KMETA_VERSION

		# ----------------------
		# User-defined packages
		# ----------------------
		if [ -d packages/$RELEASE$distro_release ]; then
			for PKG in packages/$RELEASE$distro_release/*; do
				PKGNAME=${PKG##*/}
				PKG_VERSION=$(sed '1{s/.*(\(.*\)).*/\1/;q}' $PKG/debian/changelog)
				REPO_VERSION=$(reprepro -b $REPO_DEST -T deb list $RELEASE$distro_release $PKGNAME | cut -f 3 -d ' ' |head -n 1 ) || true
				if [ -z "$REPO_VERSION" ] || dpkg --compare-versions $PKG_VERSION gt $REPO_VERSION; then
					rm -rf $CHROOTDIR/$WORK_DIR
					mkdir -p $CHROOTDIR/$WORK_DIR
					cp -r $PKG $CHROOTDIR/$WORK_DIR
					# What are the packages build-deps?
					PKG_BUILD_DEPS=$(chroot $CHROOTDIR bash -c "cd $WORK_DIR/$PKGNAME && dpkg-checkbuilddeps 2>&1 |sed -e 's/ *([^)]*)//g' | cut -d ' ' -f 5-")
					chroot $CHROOTDIR bash -c "cd $WORK_DIR/$PKGNAME && apt-get -y install $PKG_BUILD_DEPS"
					chroot $CHROOTDIR bash -c "cd $WORK_DIR/$PKGNAME && $CCACHE_PREFS dpkg-buildpackage $DPKGOPTS"
					reprepro -Vb $REPO_DEST include $RELEASE$distro_release $CHROOTDIR/$WORK_DIR/*.changes
				fi
			done
		fi

	done
done

# --------------------
# Extra meta packages
# --------------------
./gen-emeta

# --------------------------------
# Unset BUILD_ARCH so it 
# won't contaminate future runs
# --------------------------------
unset BUILD_ARCH
unset MAINT_INFO
unset DPKGOPTS

echo "do-update completed"

