#!/bin/bash

###############################################################################
#		(C) 2009-2011 hyperclock (aka Jimmy M. Coleman)
#        website	:		www.cybernux.org
#        email		:		hyperclock(at)cybernux(dot)org
#        svn		:		http://xp-dev.com/svn/ForkForge/
#        dev		:		http://dev.cybernux.org
#
###############################################################################
###############################################################################
#    ForkMason - Scripts designed to build Cybernux Linux® based on Debian.
#
#    ForkMason is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ForkMason is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General
#    Public License along with ForkMason.  If not, see
#    <http://www.gnu.org/licenses/>.
#
################################################################################
################################ INFO ##########################################
#
#       Derived from the scripts used by the gNewSense Project.
#       See the original scripts at http://gnewsense.org
#
#       Original (C) 2006 - 2009  Brian Brazil
#
#################################################################################

# ------------------------
# Get distro information
# ------------------------
. config

# ---------------------------------------
# Hard link Debian mirror and $REPO_DEST
mkdir -p $REPO_DEST/conf
# cp -aul $MIRRORLOCAL/* $REPO_DEST/

cd $REPO_DEST

cat >  conf/distributions <<EOF
Origin: $DIST_NAME
Label: $DIST_NAME
Codename: ${RELEASE}-security
Update: Upstream-security
Architectures: $REPO_ARCHES source
Components: main community bound
UDebComponents: main
SignWith: $REPO_KEY
DscIndices: Sources Release . .gz
DebOverride: override.$RELEASE-security.bin
UDebOverride: override.$RELEASE-security.bin
DscOverride: override.$RELEASE-security.src

Origin: $DIST_NAME
Label: $DIST_NAME
Codename: $RELEASE
Update: Upstream Upstream-mate
Architectures: $REPO_ARCHES source
Components: main community bound
UDebComponents: main
SignWith: $REPO_KEY
DscIndices: Sources Release . .gz
DebOverride: override.$RELEASE.bin
UDebOverride: override.$RELEASE.bin
DscOverride: override.$RELEASE.src
EOF

cat >  conf/updates <<EOF
Name: Upstream-security
Method: $UPD_MIRROR
Suite: ${MIRROR_DIST}/security
Components: main>main contrib>community non-free>bound

Name: Upstream
Method: $MIRROR
Suite: $MIRROR_DIST
Components: main>main contrib>community non-free>bound

Name: Upstream-mate
Method: $MATE_MIRROR
Suite: $MIRROR_DIST
Components: main>main
EOF

if [ 1 == $UPDATES ]; then
cat >> conf/updates <<EOF

Name: Upstream-updates
Method: $SEC_MIRROR
Suite: ${SEC_MIRROR_DIST}-updates
Components: main>main contrib>community non-free>bound
EOF

cat >>  conf/distributions <<EOF

Origin: $DIST_NAME
Label: $DIST_NAME
Codename: ${RELEASE}-updates
Update: Upstream-updates
Architectures: $REPO_ARCHES source
Components: main community bound
SignWith: $REPO_KEY
DscIndices: Sources Release . .gz
DebOverride: override.$RELEASE-updates.bin
UDebOverride: override.$RELEASE-updates.bin
DscOverride: override.$RELEASE-updates.src
EOF
fi

if [ 1 == $BACKPORTS ]; then
cat >> conf/updates <<EOF

Name: Upstream-backports
Method: $BP_MIRROR
Suite: ${MIRROR_DIST}-backports
Components: main>main contrib>community non-free>bound
EOF

cat >>  conf/distributions <<EOF

Origin: $DIST_NAME
Label: $DIST_NAME
Codename: $RELEASE-backports
Update: Upstream-backports
Architectures: $REPO_ARCHES source
Components: main community bound
SignWith: $REPO_KEY
DscIndices: Sources Release . .gz
DebOverride: override.$RELEASE-backports.bin
UDebOverride: override.$RELEASE-backports.bin
DscOverride: override.$RELEASE-backports.src
EOF
fi;


mkdir -p $REPO_DEST/cdimage
mkdir -p $REPO_DEST/apt/{var,lists/partial,cache/archives/partial}
touch $REPO_DEST/apt/status
touch conf/purge-$MIRROR_DIST
