#!/bin/bash

###############################################################################
#		(C) 2009-2011 hyperclock (aka Jimmy M. Coleman)
#        website	:		www.cybernux.org
#        email		:		hyperclock(at)cybernux(dot)org
#        svn		:		http://xp-dev.com/svn/ForkForge/
#        dev		:		http://dev.cybernux.org
#
###############################################################################
###############################################################################
#    ForkMason - Scripts designed to build Cybernux Linux® based on Debian.
#
#    ForkMason is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ForkMason is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General
#    Public License along with ForkMason.  If not, see
#    <http://www.gnu.org/licenses/>.
#
################################################################################
################################ INFO ##########################################
#
#       Derived from the scripts used by the gNewSense Project.
#       See the original scripts at http://gnewsense.org
#
#       Original (C) 2006 - 2009  Brian Brazil
#
#################################################################################
#    Copyright (C) 2006  Christian Fernandez
#################################################################################

#    based on Brian's gen-meta

# This file should be merged with gen-meta; its 99% redundant

. config

rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source kubuntu-meta$VERSION
apt-get --yes build-dep kubuntu-meta$VERSION
cd kubuntu-meta-*

for i in desktop live; do
	n=META_KDE_${i}_REMOVE
	for p in ${!n}; do
		sed -i "/^$p$/d" ${i}-$GNS_HOST_ARCH
	done;
	n=META_KDE_${i}_ADD
	for p in ${!n}; do
		echo "$p" >> ${i}-$GNS_HOST_ARCH
	done;
done;


sed -i "s/package=kubuntu/package=k${DISTRONAME_L}/;
	/^binary-indep:/,/^$/s/.* -i.*//" debian/rules
sed -i "/Package: kubuntu-base/,/^$/d; 
	s/kubuntu-/k${DISTRONAME_L}-/; 
	s/Kubuntu/k$DISTRONAME/g" debian/control
echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'k${DISTRONAME_L}${KMETA_VERSION}'#p' debian/changelog)  "Altered for $RELEASE"
sed -i "1s/^kubuntu-meta/k${DISTRONAME_L}-meta/" debian/changelog

dpkg-buildpackage $DPKGOPTS
