#!/bin/bash

###############################################################################
#		(C) 2009-2011 hyperclock (aka Jimmy M. Coleman)
#        website	:		www.cybernux.org
#        email		:		hyperclock(at)cybernux(dot)org
#        svn		:		http://xp-dev.com/svn/ForkForge/
#        dev		:		http://dev.cybernux.org
#
###############################################################################
###############################################################################
#    ForkMason - Scripts designed to build Cybernux Linux® based on Debian.
#
#    ForkMason is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ForkMason is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General
#    Public License along with ForkMason.  If not, see
#    <http://www.gnu.org/licenses/>.
#
################################################################################
################################ INFO ##########################################
#
#       Derived from the scripts used by the gNewSense Project.
#       See the original scripts at http://gnewsense.org
#
#       Original (C) 2006 - 2009  Brian Brazil
#
#################################################################################
#    Copyright (C) 2009  Karl Goetz
#################################################################################


. config

IMGDIR=$PWD/images
rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source texlive-bin
apt-get --yes build-dep texlive-bin
cd texlive-bin-*

# Find nonfree font downloader and remove it.
find ./ -name *nonfree* -exec rm -v {} +

# Remove references (as needed) in files
sed -i -e '/#60_getnonfreefonts_bash/d' debian/patches/series
sed -i -e '/getnonfreefonts/d' debian/control
sed -i -e '/getnonfreefonts-sys/d' build/source/texk/texlive/Makefile.in
sed -i -e 's/getnonfreefonts//g' build/source/texk/texlive/Makefile.in

echo | dch -D $RELEASE -v $(sed -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${TEXLIVE_BASE_VERSION}'#p' debian/changelog)  'Inserted new licence file'

dpkg-buildpackage $DPKGOPTS

