#!/bin/bash

###############################################################################
#		(C) 2009-2011 hyperclock (aka Jimmy M. Coleman)
#        website	:		www.cybernux.org
#        email		:		hyperclock(at)cybernux(dot)org
#        svn		:		http://xp-dev.com/svn/ForkForge/
#        dev		:		http://dev.cybernux.org
#
###############################################################################
###############################################################################
#    ForkMason - Scripts designed to build Cybernux Linux® based on Debian.
#
#    ForkMason is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ForkMason is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General
#    Public License along with ForkMason.  If not, see
#    <http://www.gnu.org/licenses/>.
#
################################################################################
################################ INFO ##########################################
#
#       Derived from the scripts used by the gNewSense Project.
#       See the original scripts at http://gnewsense.org
#
#       Original (C) 2006 - 2009  Brian Brazil
#
#################################################################################
#    Copyright (C) 2009  Karl Goetz
#################################################################################


. config

rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source libgsm$VERSION
apt-get --yes build-dep libgsm$VERSION
cd libgsm-*

if ! [ -f debian/README.licence ]; then
	cat << EOF >> debian/README.licence
The licence of libgsm was found to be unclear, and as such suspect when it
came to freedom (ref: http://bugs.debian.org/397047 ). Since then, upstream
clarified the licence, by adding the following text:

Since the original terms of 15 years ago maybe do not make our
intentions completely clear given today's refined usage of the legal
terms, we append this additional permission:

      Permission to use, copy, modify, and distribute this software
      for any purpose with or without fee is hereby granted,
      provided that this notice is not removed and that neither
      the authors nor the Technische Universitaet Berlin are
      deemed to have made any representations as to the suitability
      of this software for any purpose nor are held responsible
      for any defects of this software.  THERE IS ABSOLUTELY NO
      WARRANTY FOR THIS SOFTWARE.

Berkeley/Bremen, 05.04.2009
Jutta Degener
Carsten Bormann

EOF

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${LIBGSM_VERSION}'#p' debian/changelog) "Changed for $DISTRONAME"

dpkg-buildpackage $DPKGOPTS
