#!/bin/bash

###############################################################################
#		(C) 2009-2011 hyperclock (aka Jimmy M. Coleman)
#        website	:		www.cybernux.org
#        email		:		hyperclock(at)cybernux(dot)org
#        svn		:		http://xp-dev.com/svn/ForkForge/
#        dev		:		http://dev.cybernux.org
#
###############################################################################
###############################################################################
#    ForkMason - Scripts designed to build Cybernux Linux® based on Debian.
#
#    ForkMason is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ForkMason is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General
#    Public License along with ForkMason.  If not, see
#    <http://www.gnu.org/licenses/>.
#
################################################################################
################################ INFO ##########################################
#
#       Derived from the scripts used by the gNewSense Project.
#       See the original scripts at http://gnewsense.org
#
#       Original (C) 2006 - 2009  Brian Brazil
#
#################################################################################

# Get distro information
. config

# Hard link Ubuntu mirror and $REPODST
mkdir -p $REPODST/conf
# cp -aul $MIRRORLOCAL/* $REPODST/

cd $REPODST

cat >  conf/distributions <<EOF
Origin: $DISTRONAME
Label: $DISTRONAME
Codename: ${RELEASE}-security
Update: Upstream-security
Architectures: $ALL_REPO_ARCHES source
Components: main universe
UDebComponents: main
SignWith: $SIGNINGKEY
DscIndices: Sources Release . .gz
DebOverride: override.$RELEASE-security.bin
UDebOverride: override.$RELEASE-security.bin
DscOverride: override.$RELEASE-security.src

Origin: $DISTRONAME
Label: $DISTRONAME
Codename: $RELEASE
Update: Upstream
Architectures: $ALL_REPO_ARCHES source
Components: main universe
UDebComponents: main
SignWith: $SIGNINGKEY
DscIndices: Sources Release . .gz
DebOverride: override.$RELEASE.bin
UDebOverride: override.$RELEASE.bin
DscOverride: override.$RELEASE.src
EOF

cat >  conf/updates <<EOF
Name: Upstream-security
Method: $MIRROR
Suite: ${MIRRORDIST}-security
Components: main>main universe>universe
FilterList: install purge-hardy

Name: Upstream
Method: $MIRROR
Suite: $MIRRORDIST
Components: main>main universe>universe
FilterList: install purge-hardy
EOF

if [ 1 == $UPDATES ]; then
cat >> conf/updates <<EOF

Name: Upstream-updates
Method: $MIRROR
Suite: ${MIRRORDIST}-updates
Components: main>main universe>universe
FilterList: install purge-hardy
EOF

cat >>  conf/distributions <<EOF

Origin: $DISTRONAME
Label: $DISTRONAME
Codename: $RELEASE-updates
Update: Upstream-updates
Architectures: $ALL_REPO_ARCHES source
Components: main universe
UDebComponents: main
SignWith: $SIGNINGKEY
DscIndices: Sources Release . .gz
DebOverride: override.$RELEASE-updates.bin
UDebOverride: override.$RELEASE-updates.bin
DscOverride: override.$RELEASE-updates.src
EOF
fi

if [ 1 == $BACKPORTS ]; then
cat >> conf/updates <<EOF

Name: Upstream-backports
Method: $MIRROR
Suite: ${MIRRORDIST}-backports
Components: main>main universe>universe
FilterList: install purge-hardy
EOF

cat >>  conf/distributions <<EOF

Origin: $DISTRONAME
Label: $DISTRONAME
Codename: $RELEASE-backports
Update: Upstream-backports
Architectures: $ALL_REPO_ARCHES source
Components: main universe
UDebComponents: main
SignWith: $SIGNINGKEY
DscIndices: Sources Release . .gz
DebOverride: override.$RELEASE-backports.bin
UDebOverride: override.$RELEASE-backports.bin
DscOverride: override.$RELEASE-backports.src
EOF
fi;


mkdir -p $REPODST/cdimage
mkdir -p $REPODST/apt/{var,lists/partial,cache/archives/partial}
touch $REPODST/apt/status
touch conf/purge-$MIRRORDIST
