#!/bin/bash

###############################################################################
#		(C) 2009-2011 hyperclock (aka Jimmy M. Coleman)
#        website	:		www.cybernux.org
#        email		:		hyperclock(at)cybernux(dot)org
#        svn		:		http://xp-dev.com/svn/ForkForge/
#        dev		:		http://dev.cybernux.org
#
###############################################################################
###############################################################################
#    ForkMason - Scripts designed to build Cybernux Linux® based on Debian.
#
#    ForkMason is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ForkMason is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy (see docs/gpl-3.0.txt) of the GNU General
#    Public License along with ForkMason.  If not, see
#    <http://www.gnu.org/licenses/>.
#
################################################################################
################################ INFO ##########################################
#
#       Derived from the scripts used by the gNewSense Project.
#       See the original scripts at http://gnewsense.org
#
#       Original (C) 2006 - 2009  Brian Brazil
#
#################################################################################


# Generates an ISO with source packages for everytihng installed on the livecd
# Assumes that gen-livecd has been run


. config

mkdir -p $LIVECDDIR-src/$DISTRONAME_L-cdsource-$RELEASE-$GNS_HOST_ARCH-$LIVECD_VERSION
cd $LIVECDDIR-src/$DISTRONAME_L-cdsource-$RELEASE-$GNS_HOST_ARCH-$LIVECD_VERSION

dpkg --admindir=$LIVECDDIR/chroot-$GNS_HOST_ARCH/var/lib/dpkg --get-selections | awk '$2 ~ /^install$/{print $1}END{print "'"$CDSOURCE_ADD"'"}' |
xargs -- apt-get -o Dir::Etc::SourceList=$LIVECDDIR/sources.list \
	-o Dir::State::Lists=$LIVECDDIR/chroot-$GNS_HOST_ARCH/var/lib/apt/lists \
	-o Dir::State::status=$LIVECDDIR/chroot-$GNS_HOST_ARCH/var/lib/dpkg/status \
	-o Dir::Cache=$LIVECDDIR/chroot-$GNS_HOST_ARCH/var/cache/apt/ -t $RELEASE \
	--download-only source
