#!/bin/bash

# ----------------------------------------------------------------------
# ForkMasonMM			::	fork Debian Archive
# Copyright				::	(C) 2011-2012 by the Cybernux Linux® DevTeam.
# Cybernux Linux® WWW	::	http://www.cybernux.org/
# Cybernux Linux® Dev	::	http://dev.cybernux.org/
# SVN Archive			::	http://svn.berlios.de/wsvn/forkmason
# ----------------------------------------------------------------------
# Based on:
# The gNewSense Builder - http://gnewsense.org/Builder (GPLv2)
# ----------------------------------------------------------------------
# LICENSE:
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------

# -------------------------------
# Pushes the repo to the mirror
# -------------------------------

. config


date '+%s%n%c' > $REPO_DEST/dists/.last_push_repo
rsync -va $RSYNC_OPTIONS $REPO_DEST/pool $RSYNC_DEST/$DIST_NAME_SMALL/
rsync -va $RSYNC_OPTIONS --delete $REPO_DEST/dists $RSYNC_DEST/$DIST_NAME_SMALL/
# Can only delete after dists is updated
rsync -va --delete --delete-excluded $RSYNC_OPTIONS $REPO_DEST/pool $RSYNC_DEST/$DIST_NAME_SMALL/
